apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd-applications
  namespace: argo
spec:
  source:
    repoURL: https://github.com/JuananOc/helm-ops-argo-cd-applications
    targetRevision: main
    path: .
  
  project: default
  
  destination:
    name: in-cluster
    namespace: argo
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
