---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: devops
spec:
  generators:
  - list:
      elements:
      - app: guestbook
        namespace: default

  template:
    metadata:
      name: "{{`{{ app }}`}}"
    spec:
      source:
        repoURL: "https://github.com/argoproj/argocd-example-apps"
        targetRevision: master
        path: "{{`{{ app }}`}}"

      project: devops

      destination:
        name: in-cluster
        namespace: "{{`{{ namespace }}`}}"

      syncPolicy:
        automated:
          prune: true
          selfHeal: false
