---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: devops
spec:
  destinations:
    - name: in-cluster
      namespace: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - "*"